# Copyright 2024 Stacklok, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Note that this assumes read/write permissions to the session_store database
# table.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: session-expiration-purge
spec:
  schedule: {{ .Values.sessionExpirationPurgeJobSettings.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccounts.sessionExpirationPurgeJob | default "minder" }}
          containers:
          - name: purger
            image: {{ .Values.sessionExpirationPurgeJobSettings.image }}
            # restricted security context:
            # https://kubernetes.io/docs/concepts/security/pod-security-standards/
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL
            args:
              - encryption
              - purge-sessions
              - "--yes"
              - "--db-host={{ .Values.db.host }}"
              - "--config=/config/server-config.yaml"
              # We use two config files, one with all the defaults, and one with
              # additional override values from helm.  (This is a viper feature.)
              - "--config=/config/overrides.yaml"
            imagePullPolicy: {{ .Values.sessionExpirationPurgeJobSettings.imagePullPolicy }}
            resources:
              {{- toYaml .Values.sessionExpirationPurgeJobSettings.resources | nindent 14 }}
            {{- if .Values.sessionExpirationPurgeJobSettings.extraEnv }}
            env:
              {{- toYaml .Values.sessionExpirationPurgeJobSettings.extraEnv | nindent 14 }}
            {{- end }}
            volumeMounts:
              - name: config
                mountPath: /config
              {{- if .Values.sessionExpirationPurgeJobSettings.extraVolumeMounts }}
              {{- toYaml .Values.sessionExpirationPurgeJobSettings.extraVolumeMounts | nindent 14 }}
              {{- end }}
          {{- if .Values.sessionExpirationPurgeJobSettings.sidecarContainers }}
          {{- toYaml .Values.sessionExpirationPurgeJobSettings.sidecarContainers | nindent 10 }}
          {{- end }}
          restartPolicy: {{ .Values.sessionExpirationPurgeJobSettings.restartPolicy | quote }}
          volumes:
          - name: config
            configMap:
              name: minder-config
              items:
              - key: server-config.yaml
                path: server-config.yaml
              - key: overrides.yaml
                path: overrides.yaml
          {{- if .Values.sessionExpirationPurgeJobSettings.extraVolumes }}
          {{- toYaml .Values.sessionExpirationPurgeJobSettings.extraVolumes | nindent 10 }}
          {{- end }}