# Copyright 2023 Stacklok, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Default values for mediator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  httpPort: 8080
  grpcPort: 8090
  metricPort: 9090

hostname: "mediator.example.com"

db:
  host: "postgres.postgres"

aws:
  accountID: "123456789012"
  migrate:
    iamRole: "mediator_migrate_role"
  server:
    iamRole: "mediator_server_role"

migrationSettings:
  image: ko://github.com/stacklok/mediator/cmd/migrate
  imagePullPolicy: "IfNotPresent"
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 1
      memory: 300Mi

# Configurable settings for the main deployment
deploymentSettings:
  image: ko://github.com/stacklok/mediator/cmd/server
  imagePullPolicy: "IfNotPresent"
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 4
      memory: 1.5Gi
  # Additional volumes to mount
  extraVolumes: null
  # Additional volume mounts
  extraVolumeMounts: null

# Additional configuration yaml beyond what's in config.yaml.example
extra_config: |
  # Add content here

# Additional configuration yaml that's applied to the migration job
extra_config_migrate: |
  # Add even more content here
