on:
  workflow_call:
jobs:
  project_build:
    name: verify build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v3.5.0
      - name: Extract version of Go to use
        run: echo "GOVERSION=$(sed -n 's/^go \([0-9.]*\)/\1/p' go.mod)" >> $GITHUB_ENV
      - uses: actions/setup-go@v4 # v4.0.0
        with:
          go-version: 1.20.0
      - name: build
        run: make build
