# SPDX-FileCopyrightText: Copyright 2023 The Minder Authors
# SPDX-License-Identifier: Apache-2.0

name: Code Generation
on:
  push:
    branches:
      - main
      - release-*
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**.txt"
      - "images/**"
      - "LICENSE"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**.txt"
      - "images/**"
      - "LICENSE"
jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      # Install the `buf` CLI
      - uses: bufbuild/buf-action@8f4a1456a0ab6a1eb80ba68e53832e6fcfacc16c # v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: false
          archive: false
          pr_comment: false
          lint: true
          format: false
          breaking: false # Check for breaking changes in the next step
  proto-breaking-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: bufbuild/buf-action@8f4a1456a0ab6a1eb80ba68e53832e6fcfacc16c # v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: false
          archive: false
          pr_comment: false
          format: false
          breaking: true
          input: 'proto'
          breaking_against: "https://github.com/mindersec/minder.git#branch=main,subdir=proto"
  sqlc-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: "go.mod"
      - name: Make bootstrap
        run: |
          make bootstrap
      - name: Generate Go code from SQL and check for syntax errors
        shell: bash
        run: |
          make sqlc
      - name: Check for uncommitted SQLC changes
        run: |
          git diff --exit-code || (echo "Error: Uncommitted changes detected after running 'sqlc generate'. Please commit the changes and try again." && exit 1)
