name: Code Generation
on:
  push:
    branches:
      - main
      - release-*
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**.txt"
      - "images/**"
      - "LICENSE"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**.txt"
      - "images/**"
      - "LICENSE"
jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@9990c72db080fa39cf561230b8d2d7b736681f85 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # Lint your Protobuf sources
      - uses: bufbuild/buf-lint-action@06f9dd823d873146471cfaaf108a993fe00e5325 # v1
  proto-breaking-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: bufbuild/buf-setup-action@9990c72db080fa39cf561230b8d2d7b736681f85 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-breaking-action@c57b3d842a5c3f3b454756ef65305a50a587c5ba # v1
        with:
          against: "https://github.com/stacklok/minder.git#branch=main"
  sqlc-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version-file: "go.mod"
      - name: Make bootstrap
        run: |
          make bootstrap
      - name: Generate Go code from SQL and check for syntax errors
        shell: bash
        run: |
          make sqlc
      - name: Check for uncommitted SQLC changes
        run: |
          git diff --exit-code || (echo "Error: Uncommitted changes detected after running 'sqlc generate'. Please commit the changes and try again." && exit 1)
