on:
  workflow_call:
jobs:
  license-check:
    name: License boilerplate check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v3.5.0

      - uses: actions/setup-go@v4 # v4.0.0
        with:
          go-version-file: "go.mod"
      - name: Install addlicense
        run: go install github.com/google/addlicense@v1.0.0
      - name: Check license headers
        run: |
          set -e
          addlicense -l apache -c 'Stacklok, Inc' -v -ignore "pkg/generated/*" -ignore "**/database/query/**" -ignore "internal/db/*" -ignore "docs/docs/**" -ignore "docs/src/**" -ignore "docs/static/**" -ignore "pkg/controlplane/policy_types/**" -ignore "docs/build/**" -ignore "examples/**" -ignore "identity/themes/**" *
          git diff --exit-code
